version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 136.115.252.54
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_PORTS: 9092
    depends_on:
      - zookeeper
